services:
  web:
    build:
      context: .
      target: production
    image: polls-site-web
    env_file: .env
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "${HOST_BIND_IP:-127.0.0.1}:${WEB_PORT:-8000}:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: