name: Format and Lint

on:
  workflow_call:

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install Poetry
        run: pipx install poetry
        
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry config virtualenvs.create true
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: make setup
          
      - name: Run Ruff Linter
        run: make lint-check

      - name: Run Black Formatter Check
        run: make format-check
